#!/usr/bin/env node
'use strict';

/**
 * Module dependencies
 */
const program = require('commander');
const update = require('update-notifier');
const pkg = require('./package');

// Commands
const run = require('./lib/run');

// Update notify
update({pkg}).notify();

program
  .version(pkg.version)
  .description('Run livetests in a directory')
  .option('-c, --config <filename>', 'test config json file filename')
  .on('--help', function() {
    console.log('  Examples:');
    console.log();
    console.log('    $ livetest');
    console.log('    $ livetest --config=test/config.json');
    console.log();
  })
  .parse(process.argv);

run(program);
